### ISSUE TITLE
npm run dev 不能成功

### ISSUE THREAD

**Issue by heyuxin** [dwqs/vue-resume#1]
![qq 20170302152703](https://cloud.githubusercontent.com/assets/16314025/23497162/c6bdd70a-ff5c-11e6-89b9-bcf8d2eaef67.png)
![qq 20170302152722](https://cloud.githubusercontent.com/assets/16314025/23497163/c829aace-ff5c-11e6-87da-171feca2d395.png)

**Comment by dwqs** [comment]
还需要切换到client 目录 运行 gulp dev
